# Generated by Django 5.2.1 on 2025-06-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_rename_user_id_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='user_id',
        ),
    ]
